-- 코드를 입력하세요
SELECT CATEGORY, SUM(TOTAL_SALES)
FROM (SELECT DISTINCT(CATEGORY), s.TOTAL_SALES
      FROM BOOK b JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES 
                  FROM BOOK_SALES
                  WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
                  GROUP BY BOOK_ID) s ON b.BOOK_ID = s.BOOK_ID
      ORDER BY CATEGORY ASC) B
GROUP BY CATEGORY;



